### ISSUE TITLE
Excluding tests directory from check

### ISSUE THREAD

**Issue by ashrub-holvi** [seddonym/import-linter#225]
Hi! Thank you for cool project!

I am thinking about excluding test's directory from check because, at least on first steps, it's not that critical, tried to configure it in pre-commit hook
```
- repo: https://github.com/seddonym/import-linter/
  rev: "v2.0"
  hooks:
    - id: import-linter
      exclude: /tests/
```
but seems it doesn't work and probably it's expected as the tool is not file-based, is it possible to do now or, if not, do you have plans to implement something like that?
