### ISSUE TITLE
Support wildcards for modules in forbidden contracts

### ISSUE THREAD

**Issue by GitRon** [seddonym/import-linter#232]
Hi there!

I found an issue I wasn't able to resolve. I browed through the closed tickets but couldn't find a match there, so I created this ticket.

I use the import-linter (v2.0) with Django and all my Django apps live in `apps/`. When I try to use a wildcard, the contract never fails. If I put the module explicitly, it works, thus fails.

Works:

```toml
[[tool.importlinter.contracts]]
name = "Config is intependent of everything else"
type = "forbidden"
source_modules = ["apps.config"]
forbidden_modules = [
    "apps.account",
]
```

Not working:

```toml
[[tool.importlinter.contracts]]
name = "Config is intependent of everything else"
type = "forbidden"
source_modules = ["apps.config"]
forbidden_modules = [
    "apps.*",
]
```

Am I missing something? Thanks for your help!

Best from Cologne  
Ronny
