### ISSUE TITLE
Exclude specific modules from a contract?

### ISSUE THREAD

**Issue by apmorton** [seddonym/import-linter#244]
We currently have a configuration similar to below:

```toml
[tool.importlinter]
root_packages = [
  'package',
]
include_external_packages = true

[[tool.importlinter.contracts]]
name = "only allow forbidden in subpackage"
type = "forbidden"
source_modules = [
  'package',
]

forbidden_modules = [
  'forbidden',
]

ignore_imports = [
  'package.subpackage.** -> forbidden',
]
```

This works, but has an unintended (for us) side-effect: transitive imports won't violate the contract

```python
# package/thing.py
import package.subpackage.constants # should be allowed
import package.subpackage.impl # should not be allowed, but is

# package/subpackage/constants.py
XYZ = 1

# package/subpackage/impl.py
import forbidden
```

Is something like the following feasible/desirable?
```toml
[[tool.importlinter.contracts]]
name = "only allow forbidden in subpackage"
type = "forbidden"
source_modules = [
  'package',
]

ignore_modules = [
  'package.subpackage.**',
]

forbidden_modules = [
  'forbidden',
]
```

Where `ignore_modules` aren't themselves directly checked, but transitive imports through them would be.

**Comment by seddonym** [comment]
Thanks for the issue!

If I'm understanding correctly, you want to lint for the following: modules in `package` (except `package.subpackage`) must not import `forbidden`, even indirectly. Is that correct?

You could achieve already by listing of the modules in `package` that are not `package.subpackage` explicitly, e.g.

```toml
[[tool.importlinter.contracts]]
name = "only allow forbidden in subpackage"
type = "forbidden"
source_modules = [
  'package.thing',
  'package.something_else'
]
forbidden_modules = [
  'forbidden',
]
```

Providing you remembered to list all of the other modules in `source_modules` (with the exception of `subpackag=e`) then I think that would work. Admittedly it could end up being a bit verbose, so your `ignore_modules` could help with that.

I'm reluctant to add this to Import Linter, at least not yet. if you're really keen to avoid the verbosity you could make a [custom contract type](https://import-linter.readthedocs.io/en/stable/contract_types.html#custom-contract-types) that extends the forbidden contract type but automatically includes all the modules that aren't `packages.subpackage`.

Side note: is it worth reconsidering this architectural rule? Sometimes you might want to add an import of `forbidden` to a module in `subpackage`, but there might happen to be a dependency from another module in `package` that means you can't add it. It might be worth exploring a [layered architecture](https://import-linter.readthedocs.io/en/stable/contract_types.html#layers) instead - the benefit of that is it's explicit what you can and can't import from depending on what subpackage you're in. Just my 2 cents.

Hope that's helpful.
