### ISSUE TITLE
Impossible to configure contracts in subdirectory (no Python module)

### ISSUE THREAD

**Issue by GitRon** [seddonym/import-linter#269]
Hi @seddonym!

I have a folder (not a Python module) called “backend”, this is where my modules (Django apps) live. 

In the toml file I have to configure “backend.myapp”. 

## Linter setup

```toml
[tool.importlinter]
root_packages = [
    "backend.myapp",
    "backend.otherapp",
]
include_external_packages = true

[[tool.importlinter.contracts]]
name = "Django settings isn't imported directly"
type = "forbidden"
source_modules = [
    "backend.myapp",
]
forbidden_modules = [
    "backend.otherapp.settings",
]
```

## PreCommit setup

I use the import-linter via pre-commit:

````yml
  - repo: https://github.com/seddonym/import-linter
    rev: v2.3
    hooks:
      - id: import-linter
        args: [ --config=backend/pyproject.toml ]
````

And run this command:

> pre-commit run --all-files import-linter

## Issue

But in the code I import `myapp.x`. Because of this mismatch the linter finds nothing. 

How can I tell the config that the “backend” is irrelevant?

Thanks in advance and all the best from Cologne
Ronny
