### ISSUE TITLE
Feature request: pyproject.toml intergration

### ISSUE THREAD

**Issue by louwers** [seddonym/import-linter#76]
Would be cool if import-linter would intergrate with [pyproject.toml](https://snarky.ca/what-the-heck-is-pyproject-toml/) (PEP-518).

```toml
[tool.importlinter]
root_package = "myproject"

[[tool.importlinter.contract]]
name = "Foo doesn't import bar or baz"
type = "forbidden"
source_modules = [ "myproject.foo" ]
forbidden_modules = [
  "myproject.bar",
  "myproject.baz"
]
```

**Comment by seddonym** [comment]
Thanks for the suggestion! I'd be very happy to consider a PR for this.

**Comment by skarzi** [comment]
And if `pyproject.toml` will be present, what do you think about starting using `poetry` to manage dependencies and publish releases?

**Comment by seddonym** [comment]
> what do you think about starting using poetry to manage dependencies and publish releases?

From what I understand, Poetry is there to make life easier for the maintainer - and I'm not really experiencing much pain at the moment with dependency management & releases. If I've misunderstood, and there's value for end users of Import Linter, happy to consider it. It feels like it deserves a separate Github issue though - feel free to open one if so.

**Comment by skarzi** [comment]
Sorry, I reread this issue and I notice that I misunderstood it :smile: 
I will open new one specifically about `poetry` :+1:

**Comment by kasium** [comment]
@skarzi do you plan to open a PR for this? If no @seddonym I'm happy to give it a try if you don't mind :-)

**Comment by skarzi** [comment]
@kasium feel free to start working on this because currently, I'm short on time

**Comment by kasium** [comment]
Thanks, I'll try to work on it in the next weeks

**Comment by kasium** [comment]
@seddonym @skarzi can you please let me know what you think about this config layout

```toml
[tool.importlinter]
root_package = "importlinter"

[[tool.importlinter.contracts]]
name = "Layered architecture"
type = "layers"
containers = [
    "importlinter",
]
layers = [
    "cli",
    "adapters",
    "contracts",
    "application",
    "domain",
]

[[tool.importlinter.contracts]]
name = "Layered architecture2"
```

It is inspired by the configuration mypy uses for toml. It makes parsing quite easy as you can see in the parsed data
````json
{
	"importlinter": {
		"root_package": "importlinter",
		"contracts": [
			{
				"name": "Layered architecture",
				"type": "layers",
				"containers": [
					"importlinter"
				],
				"layers": [
					"cli",
					"adapters",
					"contracts",
					"application",
					"domain"
				]
			},
			{
				"name": "Layered architecture2"
			}
		]
	}
}
``
